plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.gradleup.shadow' version '8.3.5'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		url 'https://repo.hypixel.net/repository/Hypixel'
	}
	maven {
		name "FDD Maven"
		url "https://maven.firstdark.dev/releases"
	}

	maven {
		url 'https://jitpack.io'
	}
	maven {
		url 'https://repo.viaversion.com/'
	}
	mavenCentral()
}

sourceSets {
	main {
		java.srcDirs = ['src/client/java']
		resources.srcDirs = ['src/client/resources']
	}
}

loom {
	mods {
		"gui" {
			sourceSet sourceSets.main
		}
	}
}
def lwjglVersion = "3.4.1"
configurations {
	shadow
	implementation.extendsFrom shadow
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	shadow "com.github.LabyStudio:java-spotify-api:+"
	include "com.github.LabyStudio:java-spotify-api:+"
	shadow "org.ow2.asm:asm:9.6"
	implementation "org.ow2.asm:asm:9.6"
	shadow "org.ow2.asm:asm-commons:9.6"
	implementation "org.ow2.asm:asm-commons:9.6"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.name}"}
	}

	from sourceSets.main.output

	manifest {
		attributes(
			'Premain-Class': 'com.haloclient.client.agent.HaloAgent',
			'Agent-Class': 'com.haloclient.client.agent.HaloAgent',
			'Can-Redefine-Classes': 'true',
			'Can-Retransform-Classes': 'true'
		)
	}
}

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

tasks.named('shadowJar', ShadowJar) {
	configurations = [project.configurations.shadow]
	archiveClassifier.set('shadow')
	from sourceSets.main.output
	manifest {
		attributes(
			'Premain-Class': 'com.haloclient.client.agent.HaloAgent',
			'Agent-Class': 'com.haloclient.client.agent.HaloAgent',
			'Can-Redefine-Classes': 'true',
			'Can-Retransform-Classes': 'true'
		)
	}
}

// tasks.named('remapJar') {
// 	dependsOn(shadowJar)
// 	inputFile.set(shadowJar.archiveFile)
// }

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}